"""Mock documentation generator.

Produces ``mock-documentation.md`` describing all mocked APIs, their
endpoints, success/error/empty response examples, and instructions for
switching between mock and real modes.
"""

from __future__ import annotations

import asyncio
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from rich.console import Console

console = Console()


# ---------------------------------------------------------------------------
# MockDocGenerator
# ---------------------------------------------------------------------------

class MockDocGenerator:
    """Generates ``mock-documentation.md`` documenting all mocked APIs.

    The document covers:
    - Overview of the mocking strategy
    - Frontend mocks (MSW handlers)
    - Backend mocks (pytest fixtures / httpx MockTransport)
    - Per-endpoint mock behaviours with success, error, and empty responses
    - Instructions for switching between mock and real APIs
    """

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def generate(
        self,
        architecture: dict[str, Any],
        mock_handlers: list[dict[str, Any]],
        output_path: str | Path,
    ) -> Path:
        """Generate mock documentation markdown.

        Parameters
        ----------
        architecture:
            Architecture dict with ``project_name``, ``api_contracts``,
            ``external_apis``, ``port_allocation``, etc.
        mock_handlers:
            List of mock handler dicts, each with keys:
            ``name``, ``type`` (``frontend`` | ``backend``),
            ``method``, ``path``, ``description``,
            ``success_response``, ``error_response``,
            ``empty_response``.
        output_path:
            File path where the markdown will be written.

        Returns
        -------
        Path
            Absolute path to the written file.
        """
        output = Path(output_path).resolve()
        output.parent.mkdir(parents=True, exist_ok=True)

        content = self._render(architecture, mock_handlers)

        loop = asyncio.get_running_loop()
        await loop.run_in_executor(None, output.write_text, content, "utf-8")

        console.print(f"[green]Mock documentation written to {output}[/green]")
        return output

    # ------------------------------------------------------------------
    # Rendering
    # ------------------------------------------------------------------

    def _render(
        self,
        arch: dict[str, Any],
        mock_handlers: list[dict[str, Any]],
    ) -> str:
        """Render the complete mock documentation markdown."""
        project_name = arch.get("project_name", "Project")
        external_apis = arch.get("external_apis", [])
        sections: list[str] = []

        # Header
        sections.append(f"# {project_name} -- Mock Documentation")
        sections.append("")
        sections.append(
            f"> Generated by NC Dev System on "
            f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"
        )
        sections.append("")

        # Table of contents
        sections.append("## Table of Contents")
        sections.append("")
        sections.append("1. [Overview](#overview)")
        sections.append("2. [Mocking Strategy](#mocking-strategy)")
        sections.append("3. [Switching Between Mock and Real APIs](#switching-between-mock-and-real-apis)")
        sections.append("4. [Frontend Mocks (MSW)](#frontend-mocks-msw)")
        sections.append("5. [Backend Mocks (pytest)](#backend-mocks-pytest)")
        if external_apis:
            sections.append("6. [External API Mocks](#external-api-mocks)")
        sections.append("")

        # Overview
        sections.append("## Overview")
        sections.append("")
        sections.append(
            "This project uses a comprehensive mocking strategy to enable "
            "development and testing without external dependencies. All API "
            "calls are intercepted and served with realistic mock data."
        )
        sections.append("")

        fe_handlers = [h for h in mock_handlers if h.get("type") == "frontend"]
        be_handlers = [h for h in mock_handlers if h.get("type") == "backend"]

        sections.append("| Layer | Technology | Mock Handlers |")
        sections.append("|-------|-----------|---------------|")
        sections.append(
            f"| Frontend | MSW (Mock Service Worker) | {len(fe_handlers)} handlers |"
        )
        sections.append(
            f"| Backend | pytest fixtures + httpx MockTransport | {len(be_handlers)} fixtures |"
        )
        if external_apis:
            sections.append(
                f"| External | Adapter pattern + mock implementations | "
                f"{len(external_apis)} APIs mocked |"
            )
        sections.append("")

        # Mocking strategy
        sections.extend(self._render_strategy())

        # Switching instructions
        sections.extend(self._render_switching_instructions(arch))

        # Frontend mocks
        sections.extend(self._render_frontend_mocks(fe_handlers))

        # Backend mocks
        sections.extend(self._render_backend_mocks(be_handlers))

        # External API mocks
        if external_apis:
            sections.extend(
                self._render_external_mocks(external_apis, mock_handlers)
            )

        # Footer
        sections.append("---")
        sections.append("")
        sections.append(
            "*This documentation was auto-generated by the NC Dev System. "
            "For API details, see `api-documentation.md`.*"
        )
        sections.append("")

        return "\n".join(sections)

    def _render_strategy(self) -> list[str]:
        """Render the mocking strategy explanation."""
        lines: list[str] = []
        lines.append("## Mocking Strategy")
        lines.append("")
        lines.append("### Frontend (MSW)")
        lines.append("")
        lines.append(
            "The frontend uses [MSW (Mock Service Worker)](https://mswjs.io/) to "
            "intercept Axios HTTP calls at the network level. MSW runs as a "
            "Service Worker in the browser during development and as a Node.js "
            "server during tests."
        )
        lines.append("")
        lines.append("**Key files:**")
        lines.append("")
        lines.append("| File | Purpose |")
        lines.append("|------|---------|")
        lines.append("| `frontend/src/mocks/browser.ts` | MSW browser setup (development) |")
        lines.append("| `frontend/src/mocks/server.ts` | MSW server setup (tests) |")
        lines.append("| `frontend/src/mocks/handlers.ts` | Mock request handlers |")
        lines.append("")
        lines.append("### Backend (pytest)")
        lines.append("")
        lines.append(
            "The backend uses pytest fixtures with httpx `MockTransport` for "
            "integration tests and factory functions for generating test data. "
            "External API calls are mocked using the adapter pattern."
        )
        lines.append("")
        lines.append("**Key files:**")
        lines.append("")
        lines.append("| File | Purpose |")
        lines.append("|------|---------|")
        lines.append("| `backend/tests/conftest.py` | Shared fixtures (test_db, client, mock deps) |")
        lines.append("| `backend/tests/unit/` | Unit test fixtures per service |")
        lines.append("| `backend/tests/integration/` | Integration test fixtures with mock transport |")
        lines.append("")
        lines.append("### Data Generation")
        lines.append("")
        lines.append(
            "Mock data is generated using factory functions. When available, "
            "Ollama local models (qwen2.5-coder:14b for API responses, "
            "llama3.1:8b for bulk data) are used to generate realistic "
            "domain-specific test data. The system falls back to "
            "deterministic factory functions when Ollama is not available."
        )
        lines.append("")
        return lines

    def _render_switching_instructions(self, arch: dict[str, Any]) -> list[str]:
        """Render instructions for switching between mock and real APIs."""
        lines: list[str] = []
        lines.append("## Switching Between Mock and Real APIs")
        lines.append("")
        lines.append("### Environment Variable")
        lines.append("")
        lines.append(
            "The `MOCK_APIS` environment variable controls whether mock or "
            "real APIs are used:"
        )
        lines.append("")
        lines.append("```bash")
        lines.append("# Use mock APIs (default in development)")
        lines.append("MOCK_APIS=true")
        lines.append("")
        lines.append("# Use real APIs (production)")
        lines.append("MOCK_APIS=false")
        lines.append("```")
        lines.append("")
        lines.append("### Frontend")
        lines.append("")
        lines.append(
            "MSW is conditionally started in `main.tsx` based on the "
            "`VITE_MOCK_APIS` environment variable:"
        )
        lines.append("")
        lines.append("```typescript")
        lines.append("// main.tsx")
        lines.append("if (import.meta.env.VITE_MOCK_APIS === 'true') {")
        lines.append("  const { worker } = await import('./mocks/browser');")
        lines.append("  await worker.start({ onUnhandledRequest: 'bypass' });")
        lines.append("}")
        lines.append("```")
        lines.append("")
        lines.append("### Backend")
        lines.append("")
        lines.append(
            "The backend uses the adapter pattern for external service calls. "
            "The active adapter is selected via configuration:"
        )
        lines.append("")
        lines.append("```python")
        lines.append("# config.py")
        lines.append("class Settings(BaseSettings):")
        lines.append("    mock_apis: bool = True  # Set to False for production")
        lines.append("```")
        lines.append("")
        lines.append("### Docker Compose")
        lines.append("")
        lines.append("Each Docker Compose configuration sets the appropriate mode:")
        lines.append("")
        lines.append("| File | MOCK_APIS |")
        lines.append("|------|-----------|")
        lines.append("| `docker-compose.dev.yml` | `true` |")
        lines.append("| `docker-compose.test.yml` | `true` |")
        lines.append("| `docker-compose.yml` (prod) | `false` |")
        lines.append("")
        return lines

    def _render_frontend_mocks(self, handlers: list[dict[str, Any]]) -> list[str]:
        """Render the frontend mocks section."""
        lines: list[str] = []
        lines.append("## Frontend Mocks (MSW)")
        lines.append("")

        if not handlers:
            lines.append(
                "*No frontend mock handlers registered. MSW handlers will be "
                "generated during the build phase.*"
            )
            lines.append("")
            return lines

        lines.append(
            f"The following {len(handlers)} MSW handlers intercept frontend "
            f"API calls:"
        )
        lines.append("")

        # Summary table
        lines.append("| Method | Path | Description |")
        lines.append("|--------|------|-------------|")
        for h in handlers:
            method = h.get("method", "GET")
            path = h.get("path", "/")
            desc = h.get("description", "")
            lines.append(f"| `{method}` | `{path}` | {desc} |")
        lines.append("")

        # Detailed handlers
        for h in handlers:
            lines.extend(self._render_handler_detail(h, "msw"))

        return lines

    def _render_backend_mocks(self, handlers: list[dict[str, Any]]) -> list[str]:
        """Render the backend mocks section."""
        lines: list[str] = []
        lines.append("## Backend Mocks (pytest)")
        lines.append("")

        if not handlers:
            lines.append(
                "*No backend mock fixtures registered. Fixtures will be "
                "generated during the build phase.*"
            )
            lines.append("")
            return lines

        lines.append(
            f"The following {len(handlers)} pytest fixtures mock backend "
            f"dependencies:"
        )
        lines.append("")

        for h in handlers:
            lines.extend(self._render_handler_detail(h, "pytest"))

        return lines

    def _render_external_mocks(
        self,
        external_apis: list[Any],
        all_handlers: list[dict[str, Any]],
    ) -> list[str]:
        """Render the external API mocks section."""
        lines: list[str] = []
        lines.append("## External API Mocks")
        lines.append("")
        lines.append(
            "External APIs are mocked using the adapter pattern. Each "
            "external service has a mock adapter that returns predefined "
            "responses during development and testing."
        )
        lines.append("")

        for ext in external_apis:
            if isinstance(ext, str):
                ext_name = ext
                ext_url = ""
            else:
                ext_name = ext.get("name", "Unknown")
                ext_url = ext.get("base_url", "")

            lines.append(f"### {ext_name}")
            lines.append("")
            if ext_url:
                lines.append(f"**Real Base URL:** `{ext_url}`")
                lines.append("")

            # Find handlers for this external API
            ext_handlers = [
                h for h in all_handlers
                if h.get("external_api") == ext_name
            ]

            if ext_handlers:
                lines.append("**Mocked Endpoints:**")
                lines.append("")
                for h in ext_handlers:
                    lines.extend(self._render_handler_detail(h, "adapter"))
            else:
                lines.append(
                    f"*Mock handler details for {ext_name} will be generated "
                    f"during the build phase.*"
                )
                lines.append("")

        return lines

    def _render_handler_detail(
        self, handler: dict[str, Any], style: str
    ) -> list[str]:
        """Render detailed documentation for a single mock handler."""
        lines: list[str] = []
        method = handler.get("method", "GET")
        path = handler.get("path", "/")
        name = handler.get("name", f"{method} {path}")
        desc = handler.get("description", "")

        lines.append(f"### `{method} {path}`")
        lines.append("")
        if desc:
            lines.append(desc)
            lines.append("")

        # Success response
        success = handler.get("success_response")
        if success is not None:
            lines.append("**Success Response** (200):")
            lines.append("")
            lines.append("```json")
            if isinstance(success, (dict, list)):
                lines.append(json.dumps(success, indent=2))
            else:
                lines.append(str(success))
            lines.append("```")
            lines.append("")

        # Error response
        error = handler.get("error_response")
        if error is not None:
            error_status = handler.get("error_status", 400)
            lines.append(f"**Error Response** ({error_status}):")
            lines.append("")
            lines.append("```json")
            if isinstance(error, (dict, list)):
                lines.append(json.dumps(error, indent=2))
            else:
                lines.append(str(error))
            lines.append("```")
            lines.append("")

        # Empty response
        empty = handler.get("empty_response")
        if empty is not None:
            lines.append("**Empty Response** (200):")
            lines.append("")
            lines.append("```json")
            if isinstance(empty, (dict, list)):
                lines.append(json.dumps(empty, indent=2))
            else:
                lines.append(str(empty))
            lines.append("```")
            lines.append("")

        # Implementation hint based on style
        if style == "msw":
            lines.append(f"**MSW Handler** (`frontend/src/mocks/handlers.ts`):")
            lines.append("")
            lines.append("```typescript")
            lines.append(f"http.{method.lower()}('/api/v1{path}', () => {{")
            lines.append(f"  return HttpResponse.json(/* success_response */);")
            lines.append(f"}});")
            lines.append("```")
            lines.append("")
        elif style == "pytest":
            fixture_name = name.lower().replace(" ", "_").replace("/", "_").replace("-", "_")
            lines.append(f"**pytest Fixture** (`backend/tests/conftest.py`):")
            lines.append("")
            lines.append("```python")
            lines.append(f"@pytest.fixture")
            lines.append(f"def mock_{fixture_name}():")
            lines.append(f'    """Mock {desc or name}."""')
            lines.append(f"    return {{  # success_response  }}")
            lines.append("```")
            lines.append("")

        return lines
