FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt requirements-dev.txt ./
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY . .

EXPOSE {{ ports.backend }}

CMD ["uvicorn", "app.main:app", \
     "--host", "0.0.0.0", \
     "--port", "{{ ports.backend }}", \
     "--reload", \
     "--reload-dir", "app"]
