from __future__ import annotations

from pathlib import Path

from ncdev.models import DeliveryReportDoc, HardenReportDoc, TestResultDoc
from ncdev.utils import write_text


def generate_delivery_report(
    run_id: str,
    mode: str,
    project_path: Path,
    output_dir: Path,
    test_result: TestResultDoc,
    harden_report: HardenReportDoc,
) -> DeliveryReportDoc:
    docs_dir = output_dir / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)

    usage = docs_dir / "usage-guide.md"
    build = docs_dir / "build-report.md"
    api = docs_dir / "api-documentation.md"

    write_text(
        usage,
        "# Usage Guide\n\nGenerated by NC Dev System delivery pipeline.\n",
    )
    write_text(
        api,
        "# API Documentation\n\nBaseline API docs generated; expand per feature endpoints.\n",
    )
    write_text(
        build,
        (
            "# Build Report\n\n"
            f"- Run ID: {run_id}\n"
            f"- Mode: {mode}\n"
            f"- Tests passed: {test_result.passed}\n"
            f"- Hardening checks: {harden_report.checks}\n"
        ),
    )

    limitations = []
    if not test_result.passed:
        limitations.append("Some tests failed; see test-result.json for details.")

    return DeliveryReportDoc(
        run_id=run_id,
        mode=mode,
        project_path=str(project_path),
        summary="Delivery package generated.",
        artifacts=[str(usage), str(api), str(build)],
        known_limitations=limitations,
    )
